services:
  pgvector:
    image: "pgvector/pgvector:pg16"
    environment:
      - "POSTGRES_DB=barondb"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=1234"
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "5432:5432"
