spring.application.name=SpringAiCode

spring.ai.openai.api-key=${OPENAI_API_KEY}
# to select model of embeding(how embeding appears)
spring.ai.openai.embedding.options.model=text-embedding-ada-002
#make the create the schema
spring.ai.vectorstore.pgvector.initialize-schema=true
#not relying on defaults,declare the dimensions
spring.ai.vectorstore.pgvector.dimensions=1536

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.main.allow-bean-definition-overriding=true
